kubernetes:
  host: https://kubernetes.default

helloworld:
  namespace: test
  image:
    name: tutum/hello-world
    tag: latest
    pullPolicy: IfNotPresent
  service:
    ingressClass: internal-ingress
