sonarr:
  ingress:
    main:
      enabled: true
      ingressClassName: "traefik"
      hosts:
      - host: "sonarr.myplayk8s.live"
        paths:
        - path: /
          backend:
            serviceName: sonarr
            servicePort: 8989

  image:
    repository: linuxserver/sonarr
    tag: 4.0.0-develop

  persistence:
    config:
      enabled: true
      type: hostPath
      mountPath:  /config
      hostPath: /home/chevalier/Workspace/k8s_home/components/sonarr/config
    data:
      enabled: true
      type: pvc
      storageClass: nfs
      accessMode: "ReadWriteMany"
      size: 400Gi

