flaresolverr:
  ingress:
    main:
      enabled: true
      ingressClassName: "traefik"
      hosts:
      - host: "flaresolverr.myplayk8s.live"
        paths:
        - path: /
          backend:
            serviceName: flaresolverr
            servicePort: 9117

  image:
    repository: ngosang/flaresolverr
    tag: 3.2.2


  persistence:
    config:
      enabled: true
      type: hostPath
      mountPath: /config
      hostPath: /home/chevalier/Workspace/k8s_home/components/flaresolverr/config
