radarr:
  ingress:
    main:
      enabled: true
      ingressClassName: "traefik"
      hosts:
      - host: "radarr.myplayk8s.live"
        paths:
        - path: /
          backend:
            serviceName: radarr
            servicePort: 7878

  image:
    tag: v4.0.5.5981

  persistence:
    config:
      enabled: true
      type: hostPath
      mountPath:  /config
      hostPath: /home/chevalier/Workspace/k8s_home/components/radarr/config
    data:
      enabled: true
      type: pvc
      storageClass: nfs
      accessMode: "ReadWriteMany"
      size: 400Gi

