ingressClass:
  enabled: true

additionalArguments:
- --providers.kubernetesingress.ingressclass=traefik

service:
  enabled: true
  type: NodePort

ports:
  web:
    port: 8000
    expose: true
    exposedPort: 80
    protocol: TCP
    nodePort: 30000
