apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: version-discover-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: version-discover-sa # "name" is case sensitive
  namespace: version-discover
roleRef:
  kind: ClusterRole
  name: version-discover-clusterrole
  apiGroup: rbac.authorization.k8s.io
