apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: version-discover
  name: version-discover-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "deployments"]
  verbs: ["get", "watch", "list"]
