apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gorunner-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "read"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments/scale"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
