jellyfin:
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.tls: "true"
      ingressClassName: "traefik"
      hosts:
      - host: "jellyfin.myplayk8s.live"
        paths:
        - path: /
          backend:
            serviceName: jellyfin
            servicePort: 8096
      tls:
       - secretName: ingress-tls
         hosts:
           - "*.myplayk8s.live"

  image:
    repository: linuxserver/jellyfin
    tag: 10.8.11

  persistence:
    config:
      enabled: true
      type: hostPath
      mountPath:  /config
      hostPath: /home/chevalier/Workspace/k8s_home/components/jellyfin/config
    data:
      enabled: true
      type: pvc
      storageClass: nfs
      accessMode: "ReadWriteMany"
      size: 400Gi

