onechart: 
  image:
    repository: linuxserver/kodi-headless
    tag: Isengard
  ingress:
    annotations:
      kubernetes.io/ingress.class: traefik
    host: kodi.myplayk8s.live
  containerPort: 8080
