---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 2048-ingress
  namespace: game-2048
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  - host: game.myplayk8s.live
    http:
      paths:
      - path: /
        backend:
          service:
            name: service-2048
            port:
              number: 80
        pathType: Prefix
  tls:
  - hosts:
    - "*.myplayk8s.live"
    secretName: ingress-tls
