---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: 2048-ingress
  namespace: game-2048
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.frontend.rule.type: PathPrefixStrip
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - secretName: game-tls
      hosts:
        - game.playk8s.live
  rules:
  - host: game.playk8s.live
    http:
      paths:
      - path: /
        backend:
          serviceName: service-2048
          servicePort: 80
