apiVersion: v1
data:
  repositories: |
    - name: bitnami
      type: helm
      url: https://charts.bitnami.com/bitnami
    - name: redhat
      type: helm
      url: https://redhat-developer.github.io/redhat-helm-charts
    - name: k8s-at-home
      type: helm
      url: https://k8s-at-home.com/charts/
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd

