---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  - host: argocd.myplayk8s.live
    http:
      paths:
      - path: /
        backend:
          service:
            name: argocd-server
            port: 
              number: 80
        pathType: Prefix
  tls:
    - secretName: ingress-tls
      hosts:
        - "*.myplayk8s.live"
