---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: argocd.myplayk8s.live
    http:
      paths:
      - path: /
        backend:
          service:
            name: argocd-server
            port: 
              number: 80
        pathType: Prefix
