allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: nfs
    meta.helm.sh/release-namespace: default
  labels:
    app: nfs-subdir-external-provisioner
    app.kubernetes.io/managed-by: Helm
    chart: nfs-subdir-external-provisioner-4.0.16
    heritage: Helm
    release: nfs
  name: nfs
parameters:
  archiveOnDelete: "false"
  pathPattern: ""
provisioner: cluster.local/nfs-nfs-subdir-external-provisioner
reclaimPolicy: Delete
volumeBindingMode: Immediate
