---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent
spec:
  destination:
    namespace: qbittorrent
    server: https://kubernetes.default.svc
  project: k8shome
  source:
    path: components/qbittorrent/chart
    repoURL: https://github.com/clemcvl/k8s_home
    targetRevision: argo_subchart_test
  destination:
    namespace: qbittorrent
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
