---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs-cc
  labels:
    type: nas-video  
spec:
  storageClassName: ""
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.2
    path: /srv/nfs
