apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
spec:
  project: default
  source:
    chart: radarr
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: 15.2.0
    helm:
      releaseName: radarr
  destination:
    server: https://kubernetes.default.svc
    namespace: radarr
