ingress:
  main:
    enabled: true
    ingressClassName: "traefik"
    hosts:
    - host: "flaresolverr.playk8s.live"
      paths:
      - path: /
        backend:
          serviceName: flaresolverr
          servicePort: 9117

image:
  tag: v2.2.1


persistence:
  config:
    enabled: true
    type: hostPath
    mountPath: /config
    hostPath: /home/chevalier/Workspace/k8s_home/components/flaresolverr/config
