---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: minio-operator
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: minio.playk8s.live
    http:
      paths:
      - path: /
        backend:
          serviceName: console
          servicePort: 9090
